package com.dbsys.rs.client.frame;

import com.dbsys.rs.client.EventController;
import com.dbsys.rs.client.PasienTableFrame;
import com.dbsys.rs.connector.ServiceException;
import com.dbsys.rs.connector.service.PelayananService;
import com.dbsys.rs.lib.DateUtil;
import com.dbsys.rs.lib.entity.Pasien;
import javax.swing.JOptionPane;

/**
 *
 * @author Deddy Christoper Kakunsi
 */
public class FramePasienKeluar extends javax.swing.JFrame {

    private final PelayananService pelayananService = PelayananService.getInstance(EventController.host);
    private Pasien pasien;
    
    private final PasienTableFrame frame;
    
    /**
     * Creates new form FramePasienKeluar
     * 
     * @param pasien
     * @param frame
     * 
     * @throws com.dbsys.rs.connector.ServiceException pasien atau frame null.
     */
    public FramePasienKeluar(Pasien pasien, PasienTableFrame frame) throws ServiceException {
        initComponents();
        setSize(330, 220);
        
        if (pasien == null)
            throw new ServiceException("Silahkan pilih pasien");
        this.pasien = pasien;
        
        if (frame == null)
            throw new ServiceException("Frame null");
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBiayaTambahan = new javax.swing.JTextField();
        txtKeterangan = new javax.swing.JTextField();
        btnPasienKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("PASIEN KELUAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel14.setText("Keterangan");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 25));

        txtBiayaTambahan.setText("0");
        getContentPane().add(txtBiayaTambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 25));

        txtKeterangan.setText("-");
        getContentPane().add(txtKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 25));

        btnPasienKeluar.setText("OK");
        btnPasienKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPasienKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 30));

        jLabel4.setText("Biaya Tambahan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasienKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienKeluarActionPerformed
        this.dispose();
        
        String tambahan = txtBiayaTambahan.getText();
        String keterangan = txtKeterangan.getText();

        try {
            pelayananService.keluarSal(pasien, DateUtil.getDate(), DateUtil.getTime(), Long.valueOf(tambahan), keterangan);

            JOptionPane.showMessageDialog(this, "Berhasil!");
            frame.reloadTablePasien();
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnPasienKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPasienKeluar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBiayaTambahan;
    private javax.swing.JTextField txtKeterangan;
    // End of variables declaration//GEN-END:variables
}
