package com.dbsys.rs.client.frame;

import com.dbsys.rs.client.DateUtil;
import com.dbsys.rs.client.entity.Penduduk;
import com.dbsys.rs.connector.ServiceException;
import com.dbsys.rs.connector.service.PendudukService;
import java.awt.Color;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Deddy Christoper Kakunsi
 */
public final class TambahPasien extends javax.swing.JFrame {

    private final PendudukService pendudukService = PendudukService.getInstance();
    private Penduduk penduduk;
    
    /**
     * Creates new form TambahPasien
     */
    public TambahPasien() {
        initComponents();
        setData(null);
        setCustomSize();
    }
    
    /**
     * Creates new form TambahPasien
     * @param penduduk
     */
    public TambahPasien(Penduduk penduduk) {
        initComponents();
        setData(penduduk);
        setCustomSize();
    }
    
    private void setCustomSize() {
        this.setSize(450, 650);
    }
    
    private void setData(Penduduk penduduk) {
        if (penduduk == null) {
            txtPendudukKode.setText(Penduduk.createKode());
            txtPendudukNik.setText(null);
            txtPendudukNama.setText(null);
            cbPendudukKelamin.setSelectedIndex(0);
            txtPendudukTanggalLahir.setSelectedDate(null);
            txtPendudukDarah.setText(null);
            txtPendudukAgama.setText(null);
            txtPendudukTelepon.setText(null);
            txtPendudukAlamat.setText(null);
            txtPendudukPekerjaan.setText(null);
            txtPendudukJenisKartu.setText(null);

            Calendar now = Calendar.getInstance();
            now.setTime(DateUtil.getDate());
            txtPendudukTanggalDaftar.setSelectedDate(now);
        } else {
            txtPendudukKode.setText(penduduk.getKode());
            txtPendudukNik.setText(penduduk.getNik());
            txtPendudukNama.setText(penduduk.getNama());
            cbPendudukKelamin.setSelectedItem(penduduk.getKelamin().toString());
            txtPendudukDarah.setText(penduduk.getDarah());
            txtPendudukAgama.setText(penduduk.getAgama());
            txtPendudukTelepon.setText(penduduk.getTelepon());
            txtPendudukAlamat.setText(penduduk.getAlamat());
            txtPendudukPekerjaan.setText(penduduk.getPekerjaan());
            txtPendudukJenisKartu.setText(penduduk.getJenisKartu());

            Calendar tanggalLahir = Calendar.getInstance();
            tanggalLahir.setTime(penduduk.getTanggalLahir());
            txtPendudukTanggalLahir.setSelectedDate(tanggalLahir);

            if (penduduk.getTanggalDaftar() != null) {
                Calendar tanggalDaftar = Calendar.getInstance();
                tanggalDaftar.setTime(penduduk.getTanggalDaftar());
                txtPendudukTanggalDaftar.setSelectedDate(tanggalDaftar);
            }
        }

        this.penduduk = penduduk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPendudukKode = new javax.swing.JTextField();
        txtPendudukNik = new javax.swing.JTextField();
        txtPendudukNama = new javax.swing.JTextField();
        cbPendudukKelamin = new javax.swing.JComboBox();
        txtPendudukDarah = new javax.swing.JTextField();
        txtPendudukAgama = new javax.swing.JTextField();
        txtPendudukTelepon = new javax.swing.JTextField();
        txtPendudukTanggalLahir = new datechooser.beans.DateChooserCombo();
        txtPendudukTanggalDaftar = new datechooser.beans.DateChooserCombo();
        txtPendudukAlamat = new javax.swing.JTextField();
        txtPendudukPekerjaan = new javax.swing.JTextField();
        txtPendudukJenisKartu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnPendudukClean = new javax.swing.JButton();
        btnPendudukSimpan = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TAMBAH REKAM MEDIK");
        setMaximumSize(new java.awt.Dimension(437, 605));
        setMinimumSize(new java.awt.Dimension(437, 605));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDetail.setBackground(Utama.colorTransparentPanel);
        pnlDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATA REKAM MEDIK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlDetail.setBackground(new Color(0,0,0,20));
        pnlDetail.setLayout(null);

        jLabel4.setText("NO. MEDREK");
        pnlDetail.add(jLabel4);
        jLabel4.setBounds(20, 30, 100, 25);

        jLabel5.setText("NO. JAMINAN");
        pnlDetail.add(jLabel5);
        jLabel5.setBounds(20, 60, 100, 25);

        jLabel6.setText("NAMA");
        pnlDetail.add(jLabel6);
        jLabel6.setBounds(20, 90, 100, 25);

        jLabel7.setText("KELAMIN");
        pnlDetail.add(jLabel7);
        jLabel7.setBounds(20, 120, 100, 25);

        jLabel8.setText("TANGGAL LAHIR");
        pnlDetail.add(jLabel8);
        jLabel8.setBounds(20, 150, 100, 25);

        jLabel9.setText("GOL. DARAH");
        pnlDetail.add(jLabel9);
        jLabel9.setBounds(20, 180, 100, 25);

        jLabel10.setText("AGAMA");
        pnlDetail.add(jLabel10);
        jLabel10.setBounds(20, 210, 100, 25);

        jLabel11.setText("TELEPON");
        pnlDetail.add(jLabel11);
        jLabel11.setBounds(20, 240, 100, 25);

        txtPendudukKode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukKode);
        txtPendudukKode.setBounds(130, 30, 250, 25);

        txtPendudukNik.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukNik);
        txtPendudukNik.setBounds(130, 60, 250, 25);

        txtPendudukNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukNama);
        txtPendudukNama.setBounds(130, 90, 250, 25);

        cbPendudukKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih -", "PRIA", "WANITA" }));
        cbPendudukKelamin.setBorder(null);
        pnlDetail.add(cbPendudukKelamin);
        cbPendudukKelamin.setBounds(130, 120, 250, 25);

        txtPendudukDarah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukDarah);
        txtPendudukDarah.setBounds(130, 180, 250, 25);

        txtPendudukAgama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukAgama);
        txtPendudukAgama.setBounds(130, 210, 250, 25);

        txtPendudukTelepon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukTelepon);
        txtPendudukTelepon.setBounds(130, 240, 250, 25);
        pnlDetail.add(txtPendudukTanggalLahir);
        txtPendudukTanggalLahir.setBounds(130, 150, 250, 25);
        pnlDetail.add(txtPendudukTanggalDaftar);
        txtPendudukTanggalDaftar.setBounds(130, 360, 250, 25);

        txtPendudukAlamat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukAlamat);
        txtPendudukAlamat.setBounds(130, 270, 250, 25);

        txtPendudukPekerjaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukPekerjaan);
        txtPendudukPekerjaan.setBounds(130, 300, 250, 25);

        txtPendudukJenisKartu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDetail.add(txtPendudukJenisKartu);
        txtPendudukJenisKartu.setBounds(130, 330, 250, 25);

        jLabel12.setText("ALAMAT");
        pnlDetail.add(jLabel12);
        jLabel12.setBounds(20, 270, 100, 25);

        jLabel13.setText("PEKERJAAN");
        pnlDetail.add(jLabel13);
        jLabel13.setBounds(20, 300, 100, 25);

        jLabel14.setText("JENIS KARTU");
        pnlDetail.add(jLabel14);
        jLabel14.setBounds(20, 330, 100, 25);

        jLabel15.setText("TANGGAL DAFTAR");
        pnlDetail.add(jLabel15);
        jLabel15.setBounds(20, 360, 100, 25);

        getContentPane().add(pnlDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 400, 400));

        btnPendudukClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dbsys/rs/client/images/btn_reset.png"))); // NOI18N
        btnPendudukClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendudukCleanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendudukClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 80, 30));

        btnPendudukSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dbsys/rs/client/images/btn_simpan.png"))); // NOI18N
        btnPendudukSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendudukSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendudukSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 80, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dbsys/rs/client/images/bg_main.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendudukSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendudukSimpanActionPerformed
        if (penduduk == null)
            penduduk = new Penduduk();

        String kelamin = cbPendudukKelamin.getSelectedItem().toString();

        Calendar calendarTanggalLahir = txtPendudukTanggalLahir.getSelectedDate();
        long lTimeTanggalLahir = calendarTanggalLahir.getTimeInMillis();

        Calendar calendarTanggalDaftar = txtPendudukTanggalDaftar.getSelectedDate();
        long lTimeTanggalDaftar = calendarTanggalDaftar.getTimeInMillis();

        penduduk.setKode(txtPendudukKode.getText());
        penduduk.setNik(txtPendudukNik.getText().equals("") ? null : txtPendudukNik.getText());
        penduduk.setNama(txtPendudukNama.getText());
        penduduk.setKelamin(Penduduk.Kelamin.valueOf(kelamin));
        penduduk.setTanggalLahir(new Date(lTimeTanggalLahir));
        penduduk.setDarah(txtPendudukDarah.getText());
        penduduk.setAgama(txtPendudukAgama.getText());
        penduduk.setTelepon(txtPendudukTelepon.getText());
        penduduk.setAlamat(txtPendudukAlamat.getText());
        penduduk.setPekerjaan(txtPendudukPekerjaan.getText());
        penduduk.setJenisKartu(txtPendudukJenisKartu.getText());
        penduduk.setTanggalDaftar(new Date(lTimeTanggalDaftar));

        try {
            penduduk = pendudukService.simpan(penduduk);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Berhasil menyimpan data rekam medik");
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnPendudukSimpanActionPerformed

    private void btnPendudukCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendudukCleanActionPerformed
        setData(null); // Reset Form
    }//GEN-LAST:event_btnPendudukCleanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPendudukClean;
    private javax.swing.JButton btnPendudukSimpan;
    private javax.swing.JComboBox cbPendudukKelamin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JTextField txtPendudukAgama;
    private javax.swing.JTextField txtPendudukAlamat;
    private javax.swing.JTextField txtPendudukDarah;
    private javax.swing.JTextField txtPendudukJenisKartu;
    private javax.swing.JTextField txtPendudukKode;
    private javax.swing.JTextField txtPendudukNama;
    private javax.swing.JTextField txtPendudukNik;
    private javax.swing.JTextField txtPendudukPekerjaan;
    private datechooser.beans.DateChooserCombo txtPendudukTanggalDaftar;
    private datechooser.beans.DateChooserCombo txtPendudukTanggalLahir;
    private javax.swing.JTextField txtPendudukTelepon;
    // End of variables declaration//GEN-END:variables
}
