package com.dbsys.rs.client;

/**
 *
 * @author Deddy Christoper Kakunsi
 */
public class FrameFarmasi extends javax.swing.JFrame {

    /**
     * Creates new FrameFarmasi
     */
    public FrameFarmasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlBhp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBhpKeyword = new javax.swing.JTextField();
        pnlBhpDetail = new javax.swing.JPanel();
        txtBhpKode = new javax.swing.JTextField();
        txtBhpNama = new javax.swing.JTextField();
        txtBhpHarga = new javax.swing.JTextField();
        txtBhpTanggungan = new javax.swing.JTextField();
        txtBhpSatuan = new javax.swing.JTextField();
        txtBhpJumlah = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlBhpStok = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtBhpStokTanggal = new javax.swing.JTextField();
        txtBhpStokJam = new javax.swing.JTextField();
        txtBhpStokJumlah = new javax.swing.JTextField();
        btnBhpStokSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBhp = new javax.swing.JTable();
        pnlObat = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtObatKeyword = new javax.swing.JTextField();
        pnlObatDetail = new javax.swing.JPanel();
        txtObatKode = new javax.swing.JTextField();
        txtObatNama = new javax.swing.JTextField();
        txtObatHarga = new javax.swing.JTextField();
        txtObatTanggungan = new javax.swing.JTextField();
        txtObatSatuan = new javax.swing.JTextField();
        txtObatJumlah = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pnlObatStok = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtObatStokTanggal = new javax.swing.JTextField();
        txtObatStokJam = new javax.swing.JTextField();
        txtObatStokJumlah = new javax.swing.JTextField();
        btnObatStokSimpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBhp1 = new javax.swing.JTable();
        pnlResep = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPasienNik = new javax.swing.JTextField();
        txtPasienNama = new javax.swing.JTextField();
        txtPasienKelamin = new javax.swing.JTextField();
        txtPasienTanggalLahir = new javax.swing.JTextField();
        txtPasienGolonganDarah = new javax.swing.JTextField();
        txtPasienAgama = new javax.swing.JTextField();
        txtPasienTelepon = new javax.swing.JTextField();
        txtPasienTanggungan = new javax.swing.JTextField();
        txtPasienStatusRawat = new javax.swing.JTextField();
        txtPasienTanggalMasuk = new javax.swing.JTextField();
        txtPasienKode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblObat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtResepNomor = new javax.swing.JTextField();
        txtObatTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RUMAH SAKIT LIUN KENDAGE TAHUNA - FARMASI");
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jButton1.setText("RESEP");
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 10, 110, 40);

        btnStok.setText("STOK BARANG");
        jPanel2.add(btnStok);
        btnStok.setBounds(10, 60, 110, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 90, 130, 110);

        pnlBhp.setLayout(null);

        jLabel6.setText("Kata Kunci");
        pnlBhp.add(jLabel6);
        jLabel6.setBounds(10, 10, 60, 14);
        pnlBhp.add(txtBhpKeyword);
        txtBhpKeyword.setBounds(90, 10, 280, 20);

        pnlBhpDetail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBhpDetail.setLayout(null);

        txtBhpKode.setEditable(false);
        pnlBhpDetail.add(txtBhpKode);
        txtBhpKode.setBounds(160, 30, 170, 20);

        txtBhpNama.setEditable(false);
        pnlBhpDetail.add(txtBhpNama);
        txtBhpNama.setBounds(160, 60, 170, 20);

        txtBhpHarga.setEditable(false);
        txtBhpHarga.setToolTipText("");
        pnlBhpDetail.add(txtBhpHarga);
        txtBhpHarga.setBounds(160, 90, 170, 20);

        txtBhpTanggungan.setEditable(false);
        txtBhpTanggungan.setToolTipText("");
        pnlBhpDetail.add(txtBhpTanggungan);
        txtBhpTanggungan.setBounds(160, 120, 170, 20);

        txtBhpSatuan.setEditable(false);
        pnlBhpDetail.add(txtBhpSatuan);
        txtBhpSatuan.setBounds(160, 180, 170, 20);

        txtBhpJumlah.setEditable(false);
        pnlBhpDetail.add(txtBhpJumlah);
        txtBhpJumlah.setBounds(160, 150, 170, 20);

        jLabel14.setText("Kode");
        pnlBhpDetail.add(jLabel14);
        jLabel14.setBounds(30, 30, 24, 14);

        jLabel15.setText("Nama");
        pnlBhpDetail.add(jLabel15);
        jLabel15.setBounds(30, 60, 27, 14);

        jLabel16.setText("Harga");
        pnlBhpDetail.add(jLabel16);
        jLabel16.setBounds(30, 90, 29, 14);

        jLabel84.setText("Tanggungan");
        pnlBhpDetail.add(jLabel84);
        jLabel84.setBounds(30, 120, 60, 14);

        jLabel17.setText("Jumlah");
        pnlBhpDetail.add(jLabel17);
        jLabel17.setBounds(30, 150, 33, 14);

        jLabel18.setText("Satuan");
        pnlBhpDetail.add(jLabel18);
        jLabel18.setBounds(30, 180, 34, 14);

        pnlBhp.add(pnlBhpDetail);
        pnlBhpDetail.setBounds(10, 50, 360, 220);

        pnlBhpStok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBhpStok.setLayout(null);

        jLabel19.setText("Tanggal");
        pnlBhpStok.add(jLabel19);
        jLabel19.setBounds(30, 30, 38, 14);

        jLabel20.setText("Jam");
        pnlBhpStok.add(jLabel20);
        jLabel20.setBounds(30, 60, 19, 14);

        jLabel21.setText("Jumlah");
        pnlBhpStok.add(jLabel21);
        jLabel21.setBounds(30, 90, 33, 14);
        pnlBhpStok.add(txtBhpStokTanggal);
        txtBhpStokTanggal.setBounds(119, 30, 190, 20);
        pnlBhpStok.add(txtBhpStokJam);
        txtBhpStokJam.setBounds(119, 60, 190, 20);
        pnlBhpStok.add(txtBhpStokJumlah);
        txtBhpStokJumlah.setBounds(119, 90, 190, 20);

        btnBhpStokSimpan.setText("SIMPAN");
        pnlBhpStok.add(btnBhpStokSimpan);
        btnBhpStokSimpan.setBounds(240, 180, 71, 23);

        pnlBhp.add(pnlBhpStok);
        pnlBhpStok.setBounds(380, 50, 350, 220);

        tblBhp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBhp);

        pnlBhp.add(jScrollPane2);
        jScrollPane2.setBounds(10, 280, 720, 240);

        jTabbedPane1.addTab("BAHAN HABIS PAKAI", pnlBhp);

        pnlObat.setLayout(null);

        jLabel22.setText("Kata Kunci");
        pnlObat.add(jLabel22);
        jLabel22.setBounds(10, 10, 60, 14);
        pnlObat.add(txtObatKeyword);
        txtObatKeyword.setBounds(90, 10, 280, 20);

        pnlObatDetail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlObatDetail.setLayout(null);

        txtObatKode.setEditable(false);
        pnlObatDetail.add(txtObatKode);
        txtObatKode.setBounds(160, 30, 170, 20);

        txtObatNama.setEditable(false);
        pnlObatDetail.add(txtObatNama);
        txtObatNama.setBounds(160, 60, 170, 20);

        txtObatHarga.setEditable(false);
        txtObatHarga.setToolTipText("");
        pnlObatDetail.add(txtObatHarga);
        txtObatHarga.setBounds(160, 90, 170, 20);

        txtObatTanggungan.setEditable(false);
        txtObatTanggungan.setToolTipText("");
        pnlObatDetail.add(txtObatTanggungan);
        txtObatTanggungan.setBounds(160, 120, 170, 20);

        txtObatSatuan.setEditable(false);
        pnlObatDetail.add(txtObatSatuan);
        txtObatSatuan.setBounds(160, 180, 170, 20);

        txtObatJumlah.setEditable(false);
        pnlObatDetail.add(txtObatJumlah);
        txtObatJumlah.setBounds(160, 150, 170, 20);

        jLabel23.setText("Kode");
        pnlObatDetail.add(jLabel23);
        jLabel23.setBounds(30, 30, 24, 14);

        jLabel24.setText("Nama");
        pnlObatDetail.add(jLabel24);
        jLabel24.setBounds(30, 60, 27, 14);

        jLabel25.setText("Harga");
        pnlObatDetail.add(jLabel25);
        jLabel25.setBounds(30, 90, 29, 14);

        jLabel85.setText("Tanggungan");
        pnlObatDetail.add(jLabel85);
        jLabel85.setBounds(30, 120, 60, 14);

        jLabel26.setText("Jumlah");
        pnlObatDetail.add(jLabel26);
        jLabel26.setBounds(30, 150, 33, 14);

        jLabel27.setText("Satuan");
        pnlObatDetail.add(jLabel27);
        jLabel27.setBounds(30, 180, 34, 14);

        pnlObat.add(pnlObatDetail);
        pnlObatDetail.setBounds(10, 50, 360, 220);

        pnlObatStok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlObatStok.setLayout(null);

        jLabel28.setText("Tanggal");
        pnlObatStok.add(jLabel28);
        jLabel28.setBounds(30, 30, 38, 14);

        jLabel29.setText("Jam");
        pnlObatStok.add(jLabel29);
        jLabel29.setBounds(30, 60, 19, 14);

        jLabel30.setText("Jumlah");
        pnlObatStok.add(jLabel30);
        jLabel30.setBounds(30, 90, 33, 14);
        pnlObatStok.add(txtObatStokTanggal);
        txtObatStokTanggal.setBounds(119, 30, 190, 20);
        pnlObatStok.add(txtObatStokJam);
        txtObatStokJam.setBounds(119, 60, 190, 20);
        pnlObatStok.add(txtObatStokJumlah);
        txtObatStokJumlah.setBounds(119, 90, 190, 20);

        btnObatStokSimpan.setText("SIMPAN");
        pnlObatStok.add(btnObatStokSimpan);
        btnObatStokSimpan.setBounds(240, 180, 71, 23);

        pnlObat.add(pnlObatStok);
        pnlObatStok.setBounds(380, 50, 350, 220);

        tblBhp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblBhp1);

        pnlObat.add(jScrollPane3);
        jScrollPane3.setBounds(10, 280, 720, 240);

        jTabbedPane1.addTab("OBAT", pnlObat);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(150, 90, 750, 560);

        pnlResep.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResep.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel3.setText("NIK");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 30, 17, 14);

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 27, 14);

        jLabel5.setText("Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 90, 36, 14);

        jLabel7.setText("Agama");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 30, 33, 14);

        jLabel8.setText("Telepon");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 60, 38, 14);

        jLabel9.setText("Gol. Darah");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 150, 70, 14);

        jLabel10.setText("Tanggal Masuk");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 150, 80, 14);

        jLabel11.setText("Tanggal Lahir");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 120, 70, 14);

        jLabel12.setText("Tanggungan");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 90, 60, 14);

        jLabel13.setText("Status Rawat");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 120, 70, 14);

        txtPasienNik.setEditable(false);
        jPanel1.add(txtPasienNik);
        txtPasienNik.setBounds(110, 30, 210, 20);

        txtPasienNama.setEditable(false);
        jPanel1.add(txtPasienNama);
        txtPasienNama.setBounds(110, 60, 210, 20);

        txtPasienKelamin.setEditable(false);
        jPanel1.add(txtPasienKelamin);
        txtPasienKelamin.setBounds(110, 90, 210, 20);

        txtPasienTanggalLahir.setEditable(false);
        jPanel1.add(txtPasienTanggalLahir);
        txtPasienTanggalLahir.setBounds(110, 120, 210, 20);

        txtPasienGolonganDarah.setEditable(false);
        jPanel1.add(txtPasienGolonganDarah);
        txtPasienGolonganDarah.setBounds(110, 150, 210, 20);

        txtPasienAgama.setEditable(false);
        jPanel1.add(txtPasienAgama);
        txtPasienAgama.setBounds(480, 30, 230, 20);

        txtPasienTelepon.setEditable(false);
        jPanel1.add(txtPasienTelepon);
        txtPasienTelepon.setBounds(480, 60, 230, 20);

        txtPasienTanggungan.setEditable(false);
        jPanel1.add(txtPasienTanggungan);
        txtPasienTanggungan.setBounds(480, 90, 230, 20);

        txtPasienStatusRawat.setEditable(false);
        jPanel1.add(txtPasienStatusRawat);
        txtPasienStatusRawat.setBounds(480, 120, 230, 20);

        txtPasienTanggalMasuk.setEditable(false);
        jPanel1.add(txtPasienTanggalMasuk);
        txtPasienTanggalMasuk.setBounds(480, 150, 230, 20);

        pnlResep.add(jPanel1);
        jPanel1.setBounds(10, 80, 730, 190);
        pnlResep.add(txtPasienKode);
        txtPasienKode.setBounds(120, 10, 210, 20);

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblObat);

        pnlResep.add(jScrollPane1);
        jScrollPane1.setBounds(10, 280, 730, 270);

        jLabel2.setText("No. Register Pasien");
        pnlResep.add(jLabel2);
        jLabel2.setBounds(10, 10, 94, 14);

        jLabel1.setText("Nomor Resep");
        pnlResep.add(jLabel1);
        jLabel1.setBounds(10, 40, 90, 14);
        pnlResep.add(txtResepNomor);
        txtResepNomor.setBounds(120, 40, 210, 20);

        txtObatTambah.setText("Tambah Obat");
        pnlResep.add(txtObatTambah);
        txtObatTambah.setBounds(380, 40, 100, 23);

        getContentPane().add(pnlResep);
        pnlResep.setBounds(150, 90, 750, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBhpStokSimpan;
    private javax.swing.JButton btnObatStokSimpan;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlBhp;
    private javax.swing.JPanel pnlBhpDetail;
    private javax.swing.JPanel pnlBhpStok;
    private javax.swing.JPanel pnlObat;
    private javax.swing.JPanel pnlObatDetail;
    private javax.swing.JPanel pnlObatStok;
    private javax.swing.JPanel pnlResep;
    private javax.swing.JTable tblBhp;
    private javax.swing.JTable tblBhp1;
    private javax.swing.JTable tblObat;
    private javax.swing.JTextField txtBhpHarga;
    private javax.swing.JTextField txtBhpJumlah;
    private javax.swing.JTextField txtBhpKeyword;
    private javax.swing.JTextField txtBhpKode;
    private javax.swing.JTextField txtBhpNama;
    private javax.swing.JTextField txtBhpSatuan;
    private javax.swing.JTextField txtBhpStokJam;
    private javax.swing.JTextField txtBhpStokJumlah;
    private javax.swing.JTextField txtBhpStokTanggal;
    private javax.swing.JTextField txtBhpTanggungan;
    private javax.swing.JTextField txtObatHarga;
    private javax.swing.JTextField txtObatJumlah;
    private javax.swing.JTextField txtObatKeyword;
    private javax.swing.JTextField txtObatKode;
    private javax.swing.JTextField txtObatNama;
    private javax.swing.JTextField txtObatSatuan;
    private javax.swing.JTextField txtObatStokJam;
    private javax.swing.JTextField txtObatStokJumlah;
    private javax.swing.JTextField txtObatStokTanggal;
    private javax.swing.JButton txtObatTambah;
    private javax.swing.JTextField txtObatTanggungan;
    private javax.swing.JTextField txtPasienAgama;
    private javax.swing.JTextField txtPasienGolonganDarah;
    private javax.swing.JTextField txtPasienKelamin;
    private javax.swing.JTextField txtPasienKode;
    private javax.swing.JTextField txtPasienNama;
    private javax.swing.JTextField txtPasienNik;
    private javax.swing.JTextField txtPasienStatusRawat;
    private javax.swing.JTextField txtPasienTanggalLahir;
    private javax.swing.JTextField txtPasienTanggalMasuk;
    private javax.swing.JTextField txtPasienTanggungan;
    private javax.swing.JTextField txtPasienTelepon;
    private javax.swing.JTextField txtResepNomor;
    // End of variables declaration//GEN-END:variables
}
