package com.dbsys.rs.client;

import com.dbsys.rs.client.tableModel.UnitTableModel;
import com.dbsys.rs.connector.ServiceException;
import com.dbsys.rs.connector.service.UnitService;
import com.dbsys.rs.lib.entity.Unit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Frame untuk melakukan pencarian data. Dapat digunakan untuk semua data.<br />
 * Untuk membedakan pencarian kelas menggunakan {@code cls} pada constructor dan {@code frame} pemanggil,
 * supaya setelah pencarian berhasil akan kembali ke frame pemanggil tersebut.
 *
 * @author Bramwell Kasaedja
 * @author Deddy Christoper Kakunsi
 */
public class FrameCari extends javax.swing.JFrame {
    private final JFrame frame;
    private final Class<?> cls;
    
    /**
     * Creates new form formCari
     * 
     * @param frame frame yang memanggil formCari.
     * @param cls class sebagai pembeda fungsi cari.
     */
    public FrameCari(JFrame frame, Class<?> cls) {
        initComponents();
        this.frame=frame;
        this.cls=cls;
        
        if(cls.equals(Unit.class)){
            tabelUnit();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_cari_ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cari = new javax.swing.JTable();
        btn_cari_pilih = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kata Kunci");

        btn_cari_ok.setText("OK");
        btn_cari_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_okActionPerformed(evt);
            }
        });

        tbl_cari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_cari);

        btn_cari_pilih.setText("PILIH");
        btn_cari_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_pilihActionPerformed(evt);
            }
        });

        jLabel2.setText("PENCARIAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cari_pilih)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_cari_ok))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cari_pilih)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cari_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cari_okActionPerformed

    private void btn_cari_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_pilihActionPerformed
        if(cls.equals(Unit.class)){
            pilihUnit();
        }

        this.dispose();
    }//GEN-LAST:event_btn_cari_pilihActionPerformed
 
    private void pilihUnit(){
        int row = tbl_cari.getSelectedRow();
        UnitTableModel model = (UnitTableModel)tbl_cari.getModel();
        Unit unit = model.getUnit(row);

        ((FrameAdmin)frame).setUnitForOperator(unit);
    }
   
    public final void tabelUnit(){
        UnitService unitservice = UnitService.getInstance("http://localhost:8080");
 
        try {
            List<Unit> listUnit = unitservice.getAll();
            UnitTableModel model = new UnitTableModel(listUnit);
            tbl_cari.setModel(model);
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari_ok;
    private javax.swing.JButton btn_cari_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cari;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
